---
#TODO: for data generation
fonts:
  # Whether or not to enable random spacing between characters.
  random_character_spacing: False
  # The regular expression to use to generate the text
  # in the synthetic image samples.
  regex_template: '[A-Z0-9]{5,10} [A-Z0-9]{3,7}'
  # The path to the directory containing background images.
  # If provided, images in this directory will be used as
  # background for the generated text. If omitted, images
  # will have a white background.
  backgrounds_path: "../backgrounds"
  # The number of samples to generate for each font.
  samples_per_font: 50
  classes:
    - name: Test Font
      path: "../test/Test.ttf"
    - name: Other Test Font
      path: "../test/Test2.ttf"
