name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - name: Install the dependencies
        run: |
          pip install .[linting]
      - name: Run linting
        run: make lint
      - name: Run tests
        run: make test
